### PR TITLE
resolve #9

### LINKED ISSUE #9: item_OnUse() attempt to index local 'sdata' (a nil value)
I clicked with the inspection tool no a mobs_redo warthog and it crashed the game with the following message.

ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'replacer' in callback item_OnUse(): mods/replacer/inspect.lua:79: attempt to index local 'sdata' (a nil value)

### PR DESCRIPTION
**Pull request by fluxionary**
Fixes crash when using the node inspector on animals from mobs_animals as noted in Issue #9 .

### CODE REVIEW

**Comment by HybridDog** [comment]
Here's an alternative fix: https://github.com/HybridDog/replacer/commit/8da542568cb8fcfd5a5a1201fbbc6872c6c7ecc6

**Comment by fluxionary** [comment]
Thanks HybridDog. I like your fix better. I actually think I like your whole fork better...

**Comment by Golutazem** [comment]
HybridDog's fix makes the mob disappear.  It changes what the bug is, but there continues to be a bug.

**Review by Golutazem — CHANGES_REQUESTED** [review]
Either change causes the mob to be destroyed. It disappears.

**Comment by fluxionary** [comment]
> Either change causes the mob to be destroyed. It disappears.

Fascinating. I didn't notice this before because I only tested it on tamed animals, in which case it worked fine. I'm guessing that's because tamed animals generally have valid metadata. Not sure what a fix looks like yet, though.

**Pull request closed without merging**
